### ISSUE TITLE
Argo-Workflows crd's not working

### ISSUE THREAD

**Issue by Transmitt0r** [kube-rs/kopium#108]
Hey everybody,
I was trying to write a simple tool to query argo-workflows and return the status. But from all the crd's in [here](https://github.com/argoproj/argo-workflows/tree/master/manifests/base/crds/full) only the workflowtaskresults worked. Do you have any idea why I don't get any generated code (except of the use statements at the top of the file) for the other crd's?

Thank you!

**Comment by clux** [comment]
Thanks for the report. These are enormous CRDs (the main one is too big to even view on github 😓 ) and this project is still a bit early stage - there are still some bugs in here, and they are likely to be encountered on such a huge schema.

Still, this is how we can make it better; find error cases and improve by playing with this bigger dataset.

**..when time allows.**

Had a brief look at cronworkflows to confirm one and it spat out (with debug logs):

```
[2023-02-14T13:37:42Z DEBUG kopium::analyzer] with optional member sidecars of type Vec<CronWorkflowSpecWorkflowSpecTemplateDefaultsSidecars>
Error: missing items in array type
```

which i believe refers to this section in the schema:

https://github.com/argoproj/argo-workflows/blob/1322f26272b403bb300f276b808a43ba1db136dc/manifests/base/crds/full/argoproj.io_cronworkflows.yaml#L8647-L8657

so as a first step, we can extract that array item thing into a minimal test case (as per previous prs here) and hopefully we'll find isolated bits of logic that's wrong (worked in the past).

don't have time to look at this in the near future, so will put it as help wanted for now (sorry).

**Comment by Transmitt0r** [comment]
Wow nice, thanks @poelzi and @clux!
