### ISSUE TITLE
Document Unstable Rust

### ISSUE THREAD

**Issue by nyarly** [kube-rs/kopium#114]
Attempting to install from source, I run into https://github.com/rust-lang/rust/issues/87335 - fair enough, but it'd be nice to know that up front in the README or with a badge

**Comment by clux** [comment]
Hello there. This does actually build with stable rust. See e.g. the [ci job that uses stable ci image](https://github.com/kube-rs/kopium/actions/runs/4201666807/jobs/7288897337).

We use nightly for rustdoc just like the main repo, but you can totally build with stable. Be sure to `rustup update stable`!
