### ISSUE TITLE
Default version need to follow official Version Priority

### ISSUE THREAD

**Issue by imp** [kube-rs/kopium#23]
When multiple versions are described in the CRD and no `--api-version` flag is given it may be better to use the one that is specified in `storedVersion` of the `status`, rather than just the first one.

**Comment by imp** [comment]
Well, after giving this more thoughts - no, it is not better.

**Comment by teozkr** [comment]
IMO, this should either align with kubectl (whatever its behaviour is, I'll admit I haven't tried this yet) or always be required.

**Comment by imp** [comment]
Ah, here we go - [Version Priority](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-priority)

**Comment by imp** [comment]
And [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/version/helpers.go) seems to be the Golang implementation

**Comment by clux** [comment]
As a side-note, we do have code for the version policy in kube-client/discovery, but it's private: https://github.com/kube-rs/kube-rs/blob/master/kube-client/src/discovery/version.rs

**Comment by imp** [comment]
Oh, had no idea. Looks pretty similar and doesn't use `regex`, which is advantage. So let me know what you want to do with that.
