### ISSUE TITLE
parametrise outputting

### ISSUE THREAD

**Issue by clux** [kube-rs/kopium#3]
Add extra flags to clap args and handle them:

- [ ] `--hide-prelude` bool (in case people need custom crate names)
- [x]  `--api-version 1` optional setter (otherwise we should pick .first version as is) - #15 
- [ ] `--derive PartialEq` optional (multi) setter (appends to derive list per struct)

**Comment by imp** [comment]
So, for `--derive` I imaging it would be desirable to have a hardcoded list of possible traits to derive - in order to minimize chances to produce an incorrect code. The downside, of course, is that it limits flexibility. Any objections?

**Comment by clux** [comment]
Yeah, I think a hardcoded default list is sensible. `Serialize` + `Deserialize` + `Clone` + `Debug` is essentially required by `kube-derive` so those + `CustomResource` (the current derived traits) I think is a good default.

**Comment by imp** [comment]
These are derived unconditionally, correct? So `--derive` will be needed for extra traits on top of that, right?
Or do you want to override the default instead?

**Comment by clux** [comment]
Correct, those should be derived unconditionally, and the flag will be for everything else.

**Comment by imp** [comment]
Cool, on it
