### ISSUE TITLE
Kopium uses `Array` instead of `Vec` for array fields

### ISSUE THREAD

**Issue by flaper87** [kube-rs/kopium#32]
I was generating the rust code for [this CRD](https://github.com/openshift/assisted-service/blob/b650b7d5671e7552ee0e190d675375e7b3e35837/config/crd/bases/agent-install.openshift.io_agents.yaml) and noticed that the code generated is using `Array` instead of Vec for some fields.

<details>
  <summary>Here's the CRD</summary>

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.2
    installer.open-cluster-management.io/last-applied-configuration: ce84b11fb18eb5436f84845f6c462e1f6773cc46
  creationTimestamp: "2022-02-14T14:03:43Z"
  generation: 1
  labels:
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
  name: agents.agent-install.openshift.io
  resourceVersion: "270891"
  uid: 741e93d1-2f89-4945-8975-09a90983ba8f
spec:
  conversion:
    strategy: None
  group: agent-install.openshift.io
  names:
    kind: Agent
    listKind: AgentList
    plural: agents
    singular: agent
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The name of the cluster the Agent registered to.
      jsonPath: .spec.clusterDeploymentName.name
      name: Cluster
      type: string
    - description: The `Approve` state of the Agent.
      jsonPath: .spec.approved
      name: Approved
      type: boolean
    - description: The role (master/worker) of the Agent.
      jsonPath: .status.role
      name: Role
      type: string
    - description: The HostStage of the Agent.
      jsonPath: .status.progress.currentStage
      name: Stage
      type: string
    - description: The hostname of the Agent.
      jsonPath: .status.inventory.hostname
      name: Hostname
      priority: 1
      type: string
    - description: The requested hostname for the Agent.
      jsonPath: .spec.hostname
      name: Requested Hostname
      priority: 1
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: Agent is the Schema for the hosts API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AgentSpec defines the desired state of Agent
            properties:
              approved:
                type: boolean
              clusterDeploymentName:
                description: ClusterReference represents a Cluster Reference. It has
                  enough information to retrieve cluster in any namespace
                properties:
                  name:
                    description: Name is unique within a namespace to reference a
                      cluster resource.
                    type: string
                  namespace:
                    description: Namespace defines the space within which the cluster
                      name must be unique.
                    type: string
                type: object
              hostname:
                type: string
              ignitionConfigOverrides:
                description: Json formatted string containing the user overrides for
                  the host's ignition config
                type: string
              installation_disk_id:
                description: InstallationDiskID defines the installation destination
                  disk (must be equal to the inventory disk id).
                type: string
              installerArgs:
                description: Json formatted string containing the user overrides for
                  the host's coreos installer args
                type: string
              machineConfigPool:
                type: string
              role:
                description: "HostRole host role \n swagger:model host-role"
                type: string
            required:
            - approved
            - role
            type: object
          status:
            description: AgentStatus defines the observed state of Agent
            properties:
              bootstrap:
                type: boolean
              conditions:
                items:
                  description: Condition represents the state of the operator's reconciliation
                    functionality.
                  properties:
                    lastHeartbeatTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      description: ConditionType is the state of the operator's reconciliation
                        functionality.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              debugInfo:
                description: DebugInfo includes information for debugging the installation
                  process.
                properties:
                  eventsURL:
                    description: EventsURL specifies an HTTP/S URL that contains events
                      which occured during the cluster installation process
                    type: string
                  state:
                    description: Current state of the Agent
                    type: string
                  stateInfo:
                    description: Additional information pertaining to the status of
                      the Agent
                    type: string
                type: object
              hostname:
                type: string
              inventory:
                properties:
                  bmcAddress:
                    type: string
                  bmcV6Address:
                    type: string
                  boot:
                    properties:
                      currentBootMode:
                        type: string
                      pxeInterface:
                        type: string
                    type: object
                  cpu:
                    properties:
                      architecture:
                        type: string
                      clockMegahertz:
                        description: 'Name in REST API: frequency'
                        format: int64
                        type: integer
                      count:
                        format: int64
                        type: integer
                      flags:
                        items:
                          type: string
                        type: array
                      modelName:
                        type: string
                    type: object
                  disks:
                    items:
                      properties:
                        bootable:
                          type: boolean
                        byID:
                          type: string
                        byPath:
                          type: string
                        driveType:
                          type: string
                        hctl:
                          type: string
                        id:
                          type: string
                        installationEligibility:
                          properties:
                            eligible:
                              type: boolean
                            notEligibleReasons:
                              items:
                                type: string
                              type: array
                          required:
                          - notEligibleReasons
                          type: object
                        ioPerf:
                          properties:
                            syncDurationMilliseconds:
                              description: 99th percentile of fsync duration in milliseconds
                              format: int64
                              type: integer
                          type: object
                        model:
                          type: string
                        name:
                          type: string
                        path:
                          type: string
                        serial:
                          type: string
                        sizeBytes:
                          format: int64
                          type: integer
                        smart:
                          type: string
                        vendor:
                          type: string
                        wwn:
                          type: string
                      required:
                      - id
                      type: object
                    type: array
                  hostname:
                    type: string
                  interfaces:
                    items:
                      properties:
                        biosDevName:
                          type: string
                        clientID:
                          type: string
                        flags:
                          items:
                            type: string
                          type: array
                        hasCarrier:
                          type: boolean
                        ipV4Addresses:
                          items:
                            type: string
                          type: array
                        ipV6Addresses:
                          items:
                            type: string
                          type: array
                        macAddress:
                          type: string
                        mtu:
                          format: int64
                          type: integer
                        name:
                          type: string
                        product:
                          type: string
                        speedMbps:
                          format: int64
                          type: integer
                        vendor:
                          type: string
                      required:
                      - flags
                      - ipV4Addresses
                      - ipV6Addresses
                      type: object
                    type: array
                  memory:
                    properties:
                      physicalBytes:
                        format: int64
                        type: integer
                      usableBytes:
                        format: int64
                        type: integer
                    type: object
                  reportTime:
                    description: 'Name in REST API: timestamp'
                    format: date-time
                    type: string
                  systemVendor:
                    properties:
                      manufacturer:
                        type: string
                      productName:
                        type: string
                      serialNumber:
                        type: string
                      virtual:
                        type: boolean
                    type: object
                type: object
              ntpSources:
                items:
                  properties:
                    sourceName:
                      type: string
                    sourceState:
                      description: "SourceState source state \n swagger:model source_state"
                      type: string
                  type: object
                type: array
              progress:
                properties:
                  currentStage:
                    description: "HostStage host stage \n swagger:model host-stage"
                    type: string
                  progressInfo:
                    type: string
                  stageStartTime:
                    description: 'Name in REST API: stage_started_at'
                    format: date-time
                    type: string
                  stageUpdateTime:
                    description: 'Name in REST API: stage_updated_at'
                    format: date-time
                    type: string
                type: object
              role:
                description: "HostRole host role \n swagger:model host-role"
                type: string
              validationsInfo:
                additionalProperties:
                  items:
                    properties:
                      id:
                        type: string
                      message:
                        type: string
                      status:
                        type: string
                    required:
                    - id
                    - message
                    - status
                    type: object
                  type: array
                description: ValidationsInfo is a JSON-formatted string containing
                  the validation results for each validation id grouped by category
                  (network, hosts-data, etc.)
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: Agent
    listKind: AgentList
    plural: agents
    singular: agent
  conditions:
  - lastTransitionTime: "2022-02-14T14:03:43Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-02-14T14:03:43Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1

</details>

```rust

use kube::CustomResource;
use serde::{Serialize, Deserialize};
use std::collections::BTreeMap;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(group = "agent-install.openshift.io", version = "v1beta1", kind = "Agent", plural = "agents")]
#[kube(namespaced)]
#[kube(schema = "disabled")]
pub struct AgentSpec {
    pub approved: bool,
    pub clusterDeploymentName: Option<AgentClusterDeploymentName>,
    pub hostname: Option<String>,
    pub ignitionConfigOverrides: Option<String>,
    pub installation_disk_id: Option<String>,
    pub installerArgs: Option<String>,
    pub machineConfigPool: Option<String>,
    pub role: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentClusterDeploymentName {
    pub name: Option<String>,
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatus {
    pub bootstrap: Option<bool>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<AgentStatusConditions>,
    pub debugInfo: Option<AgentStatusDebugInfo>,
    pub hostname: Option<String>,
    pub inventory: Option<AgentStatusInventory>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ntpSources: Vec<AgentStatusNtpSources>,
    pub progress: Option<AgentStatusProgress>,
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub validationsInfo: BTreeMap<String, Array>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusConditions {
    pub lastHeartbeatTime: Option<String>,
    pub lastTransitionTime: Option<String>,
    pub message: Option<String>,
    pub reason: Option<String>,
    pub status: String,
    pub r#type: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusDebugInfo {
    pub eventsURL: Option<String>,
    pub state: Option<String>,
    pub stateInfo: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventory {
    pub bmcAddress: Option<String>,
    pub bmcV6Address: Option<String>,
    pub boot: Option<AgentStatusInventoryBoot>,
    pub cpu: Option<AgentStatusInventoryCpu>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub disks: Vec<AgentStatusInventoryDisks>,
    pub hostname: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub interfaces: Vec<AgentStatusInventoryInterfaces>,
    pub memory: Option<AgentStatusInventoryMemory>,
    pub reportTime: Option<String>,
    pub systemVendor: Option<AgentStatusInventorySystemVendor>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryBoot {
    pub currentBootMode: Option<String>,
    pub pxeInterface: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryCpu {
    pub architecture: Option<String>,
    pub clockMegahertz: Option<i64>,
    pub count: Option<i64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub flags: Vec<String>,
    pub modelName: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryDisks {
    pub bootable: Option<bool>,
    pub byID: Option<String>,
    pub byPath: Option<String>,
    pub driveType: Option<String>,
    pub hctl: Option<String>,
    pub id: String,
    pub installationEligibility: Option<AgentStatusInventoryDisksInstallationEligibility>,
    pub ioPerf: Option<AgentStatusInventoryDisksIoPerf>,
    pub model: Option<String>,
    pub name: Option<String>,
    pub path: Option<String>,
    pub serial: Option<String>,
    pub sizeBytes: Option<i64>,
    pub smart: Option<String>,
    pub vendor: Option<String>,
    pub wwn: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryDisksInstallationEligibility {
    pub eligible: Option<bool>,
    pub notEligibleReasons: Vec<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryDisksIoPerf {
    pub syncDurationMilliseconds: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryInterfaces {
    pub biosDevName: Option<String>,
    pub clientID: Option<String>,
    pub flags: Vec<String>,
    pub hasCarrier: Option<bool>,
    pub ipV4Addresses: Vec<String>,
    pub ipV6Addresses: Vec<String>,
    pub macAddress: Option<String>,
    pub mtu: Option<i64>,
    pub name: Option<String>,
    pub product: Option<String>,
    pub speedMbps: Option<i64>,
    pub vendor: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventoryMemory {
    pub physicalBytes: Option<i64>,
    pub usableBytes: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusInventorySystemVendor {
    pub manufacturer: Option<String>,
    pub productName: Option<String>,
    pub serialNumber: Option<String>,
    pub virtual: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusNtpSources {
    pub sourceName: Option<String>,
    pub sourceState: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AgentStatusProgress {
    pub currentStage: Option<String>,
    pub progressInfo: Option<String>,
    pub stageStartTime: Option<String>,
    pub stageUpdateTime: Option<String>,
}
```

**Comment by flaper87** [comment]
Not fully related to this issue but we may also want to catch usage of restricted keywords (note `virtual` in the generated code` and escape them with `r#`

**Comment by clux** [comment]
The curious part of the crd is this:

```yaml
              validationsInfo:
                additionalProperties:
                  items:
                    properties:
                      id:
                        type: string
                      message:
                        type: string
                      status:
                        type: string
                    required:
                    - id
                    - message
                    - status
                    type: object
                  type: array
                description: ValidationsInfo is a JSON-formatted string containing
                  the validation results for each validation id grouped by category
                  (network, hosts-data, etc.)
                type: object
```

which i take to mean that `validationsInfo` member should be a vector of ValidationInfo structs (with members `id`, `type` and `status`). it's a different way of specifying this than i'm used to, but it can probably be worked in.

**Comment by clux** [comment]
actually no, it looks like it should be a `BTreeMap<String, ValidationsInfo>` from looking at:

- https://github.com/openshift/assisted-service/blob/36774ad9829f4bcc62effbf73981dc07e9261ae8/api/common/common_types.go#L5-L15
- https://github.com/openshift/assisted-service/blob/36774ad9829f4bcc62effbf73981dc07e9261ae8/api/common/common_types.go#L5-L15

**Comment by clux** [comment]
I think I possibly have a fix for it in #33 . It depends if I have interpreted the `validationsInfo` struct correctly. @flaper87 are you able to test out this branch or give me an instance of an `agent.agent-install.openshift.io` that has the struct?

the latter would help write a better test for this weird case

**Comment by flaper87** [comment]
> are you able to test out this branch or give me an instance of an agent.agent-install.openshift.io that has the struct?

I tested the branch and it looks like it works as expected.

Here's an example of a CR

```yaml
apiVersion: agent-install.openshift.io/v1beta1
kind: Agent
metadata:
  creationTimestamp: "2022-02-14T17:55:14Z"
  finalizers:
  - agent.agent-install.openshift.io/ai-deprovision
  generation: 2
  labels:
    agent-install.openshift.io/bmh: cluster-spoke-0-master-2
    infraenvs.agent-install.openshift.io: spoke0-cluster
  name: 356201c1-b6e7-4fd1-b04e-666e317ee12b
  namespace: spoke0-cluster
  resourceVersion: "886129"
  uid: ed29cd23-6ccc-452f-a643-066abaae1c54
spec:
  approved: true
  clusterDeploymentName:
    name: spoke0-cluster
    namespace: spoke0-cluster
  hostname: cluster-spoke-0-master-2
  role: ""
status:
  bootstrap: true
  conditions:
  - lastTransitionTime: "2022-02-14T17:55:14Z"
    message: The Spec has been successfully applied
    reason: SyncOK
    status: "True"
    type: SpecSynced
  - lastTransitionTime: "2022-02-14T17:55:14Z"
    message: The agent's connection to the installation service is unimpaired
    reason: AgentIsConnected
    status: "True"
    type: Connected
  - lastTransitionTime: "2022-02-14T17:56:37Z"
    message: The agent installation stopped
    reason: AgentInstallationStopped
    status: "True"
    type: RequirementsMet
  - lastTransitionTime: "2022-02-14T17:56:37Z"
    message: The agent's validations are passing
    reason: ValidationsPassing
    status: "True"
    type: Validated
  - lastTransitionTime: "2022-02-14T18:15:20Z"
    message: 'The installation has completed: Done'
    reason: InstallationCompleted
    status: "True"
    type: Installed
  - lastTransitionTime: "2022-02-14T17:55:14Z"
    message: The agent is bound to a cluster deployment
    reason: Bound
    status: "True"
    type: Bound
  debugInfo:
    eventsURL: EVENTS_URL
    state: installed
    stateInfo: Done
  inventory:
    bmcAddress: 0.0.0.0
    bmcV6Address: ::/0
    boot:
      currentBootMode: uefi
    cpu:
      architecture: x86_64
      clockMegahertz: 2394
      count: 24
      flags:
      - fpu
      - vme
      - de
      - pse
      - tsc
      - msr
      - pae
      - mce
      - cx8
      - apic
      - sep
      - mtrr
      - pge
      - mca
      - cmov
      - pat
      - pse36
      - clflush
      - mmx
      - fxsr
      - sse
      - sse2
      - ss
      - syscall
      - nx
      - pdpe1gb
      - rdtscp
      - lm
      - constant_tsc
      - rep_good
      - nopl
      - xtopology
      - cpuid
      - tsc_known_freq
      - pni
      - pclmulqdq
      - vmx
      - ssse3
      - fma
      - cx16
      - pdcm
      - pcid
      - sse4_1
      - sse4_2
      - x2apic
      - movbe
      - popcnt
      - tsc_deadline_timer
      - aes
      - xsave
      - avx
      - f16c
      - rdrand
      - hypervisor
      - lahf_lm
      - abm
      - 3dnowprefetch
      - cpuid_fault
      - invpcid_single
      - ssbd
      - ibrs
      - ibpb
      - stibp
      - ibrs_enhanced
      - tpr_shadow
      - vnmi
      - flexpriority
      - ept
      - vpid
      - ept_ad
      - fsgsbase
      - tsc_adjust
      - bmi1
      - avx2
      - smep
      - bmi2
      - erms
      - invpcid
      - avx512f
      - avx512dq
      - rdseed
      - adx
      - smap
      - clflushopt
      - clwb
      - avx512cd
      - avx512bw
      - avx512vl
      - xsaveopt
      - xsavec
      - xgetbv1
      - xsaves
      - arat
      - umip
      - pku
      - ospke
      - avx512_vnni
      - md_clear
      - arch_capabilities
      modelName: Intel Xeon Processor (Cascadelake)
    disks:
    - byPath: /dev/disk/by-path/pci-0000:00:1f.2-ata-1
      driveType: ODD
      hctl: "0:0:0:0"
      id: /dev/disk/by-path/pci-0000:00:1f.2-ata-1
      installationEligibility:
        notEligibleReasons:
        - Disk is removable
        - Disk is too small (disk only has 109 MB, but 120 GB are required)
        - Drive type is ODD, it must be one of HDD, SSD.
      ioPerf: {}
      model: QEMU_DVD-ROM
      name: sr0
      path: /dev/sr0
      serial: QM00001
      sizeBytes: 108984320
      smart: '{"json_format_version":[1,0],"smartctl":{"version":[7,1],"svn_revision":"5049","platform_info":"x86_64-linux-4.18.0-305.19.1.el8_4.x86_64","build_info":"(local
        build)","argv":["smartctl","--xall","--json=c","/dev/sr0"],"exit_status":4},"device":{"name":"/dev/sr0","info_name":"/dev/sr0","type":"scsi","protocol":"SCSI"},"vendor":"QEMU","product":"QEMU
        DVD-ROM","model_name":"QEMU QEMU DVD-ROM","revision":"2.5+","scsi_version":"SPC-3","device_type":{"scsi_value":5,"name":"CD/DVD"},"local_time":{"time_t":1644862275,"asctime":"Mon
        Feb 14 18:11:15 2022 UTC"},"temperature":{"current":0,"drive_trip":0}}'
      vendor: QEMU
    - bootable: true
      byPath: /dev/disk/by-path/pci-0000:05:00.0
      driveType: HDD
      id: /dev/disk/by-path/pci-0000:05:00.0
      installationEligibility:
        eligible: true
        notEligibleReasons: []
      ioPerf: {}
      name: vda
      path: /dev/vda
      sizeBytes: 214748364800
      smart: '{"json_format_version":[1,0],"smartctl":{"version":[7,1],"svn_revision":"5049","platform_info":"x86_64-linux-4.18.0-305.19.1.el8_4.x86_64","build_info":"(local
        build)","argv":["smartctl","--xall","--json=c","/dev/vda"],"messages":[{"string":"/dev/vda:
        Unable to detect device type","severity":"error"}],"exit_status":1}}'
      vendor: "0x1af4"
    - byPath: /dev/disk/by-path/pci-0000:06:00.0
      driveType: HDD
      id: /dev/disk/by-path/pci-0000:06:00.0
      installationEligibility:
        eligible: true
        notEligibleReasons: []
      ioPerf: {}
      name: vdb
      path: /dev/vdb
      sizeBytes: 214748364800
      smart: '{"json_format_version":[1,0],"smartctl":{"version":[7,1],"svn_revision":"5049","platform_info":"x86_64-linux-4.18.0-305.19.1.el8_4.x86_64","build_info":"(local
        build)","argv":["smartctl","--xall","--json=c","/dev/vdb"],"messages":[{"string":"/dev/vdb:
        Unable to detect device type","severity":"error"}],"exit_status":1}}'
      vendor: "0x1af4"
    - byPath: /dev/disk/by-path/pci-0000:07:00.0
      driveType: HDD
      id: /dev/disk/by-path/pci-0000:07:00.0
      installationEligibility:
        eligible: true
        notEligibleReasons: []
      ioPerf: {}
      name: vdc
      path: /dev/vdc
      sizeBytes: 214748364800
      smart: '{"json_format_version":[1,0],"smartctl":{"version":[7,1],"svn_revision":"5049","platform_info":"x86_64-linux-4.18.0-305.19.1.el8_4.x86_64","build_info":"(local
        build)","argv":["smartctl","--xall","--json=c","/dev/vdc"],"messages":[{"string":"/dev/vdc:
        Unable to detect device type","severity":"error"}],"exit_status":1}}'
      vendor: "0x1af4"
    - byPath: /dev/disk/by-path/pci-0000:08:00.0
      driveType: HDD
      id: /dev/disk/by-path/pci-0000:08:00.0
      installationEligibility:
        eligible: true
        notEligibleReasons: []
      ioPerf: {}
      name: vdd
      path: /dev/vdd
      sizeBytes: 214748364800
      smart: '{"json_format_version":[1,0],"smartctl":{"version":[7,1],"svn_revision":"5049","platform_info":"x86_64-linux-4.18.0-305.19.1.el8_4.x86_64","build_info":"(local
        build)","argv":["smartctl","--xall","--json=c","/dev/vdd"],"messages":[{"string":"/dev/vdd:
        Unable to detect device type","severity":"error"}],"exit_status":1}}'
      vendor: "0x1af4"
    hostname: cluster-spoke-0-master-2.bare-net
    interfaces:
    - flags:
      - up
      - broadcast
      - multicast
      hasCarrier: true
      ipV4Addresses:
      - 192.168.150.204/24
      ipV6Addresses: []
      macAddress: ee:ee:ee:ee:20:2e
      mtu: 1500
      name: enp1s0
      product: "0x0001"
      speedMbps: -1
      vendor: "0x1af4"
    - flags:
      - up
      - broadcast
      - multicast
      hasCarrier: true
      ipV4Addresses:
      - 192.168.7.12/24
      ipV6Addresses: []
      macAddress: aa:aa:aa:aa:20:2a
      mtu: 1500
      name: enp2s0
      product: "0x0001"
      speedMbps: -1
      vendor: "0x1af4"
    memory:
      physicalBytes: 67108864000
      usableBytes: 65927147520
    systemVendor:
      manufacturer: Red Hat
      productName: KVM
      virtual: true
  ntpSources:
  - sourceName: mail.sebi.org
    sourceState: not_combined
  - sourceName: 79.133.44.139
    sourceState: synced
  - sourceName: x.ns.gin.ntt.net
    sourceState: not_combined
  - sourceName: h2924008.stratoserver.net
    sourceState: not_combined
  progress:
    currentStage: Done
    stageStartTime: "2022-02-14T18:15:20Z"
    stageUpdateTime: "2022-02-14T18:15:20Z"
  role: master
```

**Comment by flaper87** [comment]
@clux  thanks a bunch for addressing this issue so fast :pray:
