### ISSUE TITLE
Generates doc comments that result in syntax errors

### ISSUE THREAD

**Issue by antifuchs** [kube-rs/kopium#35]
I'm using kopium to generate type definitions for cert-manager's CRDs (https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml), and when using `--docs`, it generates doc comments that have syntax errors in them. The generated file is here: https://gist.github.com/antifuchs/533118428707296e1504e2215c77ecb8 - note line [188](https://gist.github.com/antifuchs/533118428707296e1504e2215c77ecb8#file-cert_manager-rs-L188), which is not prefixed with `///` - I suspect that's due to linebreaks in the documentation.

**Comment by clux** [comment]
Ah, thanks for this. It looks like newlines inside doc comments will indeed need to be escaped.

The code for this is in https://github.com/kube-rs/kopium/blob/b3541286f1ec691ed9d694403eae4d06d81cf281/src/main.rs#L226-L234 and it is probably a reasonably simple fix. Happy to review a quick change for this if you have time!

**Comment by antifuchs** [comment]
Hah, it just happens that I do - will give it a shot (:
