### ISSUE TITLE
add auto-complete script

### ISSUE THREAD

**Issue by clux** [kube-rs/kopium#6]
Want to add dynamic completion so that you do `kopium TAB` and you completion script does `kubectl get crds` (names only), or alternatively runs the rust code `Api<CustomResourceDefinition>` with `api.list(&Default::default()).await?` and uses that.

Think this can probably be done through [`clap-generate`](https://docs.rs/clap_generate/3.0.0-beta.5/clap_generate/), once the dynamic completion issue lands https://github.com/clap-rs/clap/issues/1232.

Until then, we switched to `structopt`, so a solution here would be:

- [ ] add a `list-crds` subcommand
- [ ] write a `kopium.complete.sh` that completes with `list-crds`
- [ ] add a `completions` subcommand that outputs the completion file

**Comment by imp** [comment]
I have a couple of ideas I want to explore regarding this ticket. Feel free to assign it to me.
