### ISSUE TITLE
allow handling IntOrString

### ISSUE THREAD

**Issue by clux** [kube-rs/kopium#8]
Currently, structs that allow `IntOrString` like kubernetes resources/limits are coerced to strings.

It would be good to handle this properly, by implementing a custom serializer/deserializer around a newtype `IntOrString`.
Currently, CRDs that use `IntOrString` might not work well with `kopium` because of this.

**Comment by imp** [comment]
Perhaps [IntOrString](https://docs.rs/k8s-openapi/0.13.1/k8s_openapi/apimachinery/pkg/util/intstr/enum.IntOrString.html) will work out of the box?

**Comment by clux** [comment]
Possibly. In the particular case of pod resources, `k8s-openapi` actually uses [`Quantity`](https://docs.rs/k8s-openapi/latest/k8s_openapi/apimachinery/pkg/api/resource/struct.Quantity.html), need to look more into how it selects these things behind the scenes.
