### ISSUE TITLE
Autogenerated output should include a comment at the top of file 

### ISSUE THREAD

**Issue by rwthompsonii** [kube-rs/kopium#85]
There should be a giant warning at the top of any generated source file like nearly every other code generator does warning people that changes to it will be overwritten.

**Comment by rwthompsonii** [comment]
Alternatively, if you do not want to do it by default, would be to add a feature that allows the user to specify a comment string to place at the top of the file, that we can optionally configure the tool to use.

**Comment by clux** [comment]
Have added a static warning to the first line in the output via:

```rust
fn print_generation_warning(&self) {
    println!("// WARNING: generated by kopium - manual changes will be overwritten");
}
```
This currently always runs, but could easily be hooked into an argv option in the future if desirable.
